const express = require('express');
const auth = require('../middleware/auth');
const CatererController = require('../controller/cartererController');
const SubscriptionController = require('../controller/subscrptionController');
const MealPlaneController = require('../controller/mealPlaneController');
const DishController = require('../controller/dishController');
const router = express.Router();

router.route('/').post(auth,CatererController.getCaterer);
router.route('/get/all').post(auth,CatererController.getAllCaterers);
router.route('/get/document/:catererID').get(auth,CatererController.getCatererDocumentByID);
router.route('/get/all/filter').post(auth,CatererController.getAllCaterersByStatus);
router.route('/dash/manager').post(auth,CatererController.dashManager);
router.route('/dash/staff').post(auth,CatererController.dashStaff);
router.route('/all/sub').post(SubscriptionController.getSubscriptionOfCaterer);
router.route('/all/mealcourse').post(MealPlaneController.allMealCourseOfCaterer);
router.route('/all/addones').post(MealPlaneController.allAddOnesOfCaterer);
router.route('/all/dish').post(DishController.allDishOfCaterer);
router.route('/accept/sub').post(auth,SubscriptionController.acceptSubscriptionRequest);
router.route('/cancel/sub').post(auth,SubscriptionController.cancelSubscriptionRequest);
router.route('/sub/details').post(SubscriptionController.getSubscriptionDetails);
router.route('/sub/info').post(SubscriptionController.getSomeSubscriptionInfo);
router.route('/sub/mealPlan').post(SubscriptionController.getSubscriptionMealPlan);
router.route('/sub/schedulemenu').post(SubscriptionController.getSubscriptionScheduleMenu);
router.route('/sub/all/dish').post(SubscriptionController.getSubscriptionDish);
router.route('/update/status').post(auth,CatererController.updateCatererStatus);
router.route('/details').post(auth,CatererController.catererDetails);
router.route('/employee').get(auth,CatererController.getEmployee);
router.route('/employee/add').post(auth,CatererController.addEmployee);
router.route('/employee/update').post(auth,CatererController.updateEmployee);
router.route('/employee/delete').post(auth,CatererController.deleteEmployee);
router.route('/employee/search').post(CatererController.searchEmployee);
router.route('/employee/:id').get(CatererController.employeeWRTId);
router.route('/financial').post(auth,CatererController.catererDetailsFinance);
router.route('/details/subscription').post(auth,CatererController.allCaterersSubscription);
router.route('/make/adjustment').post(auth,CatererController.makeAdjustment);
router.route('/make/adjustment/details').post(auth,CatererController.getmakeAdjustmentDetails);
router.route('/search').post(CatererController.search);
router.route('/all/sub/:status').post(SubscriptionController.getSubscriptionOfUsers);
router.route('/:status').post(CatererController.getCatererWRTStatus);
module.exports = router;